// web/src/components/layout/PortalLayout.vue
<template>
  <n-layout class="portal-layout">
    <n-layout-header bordered class="portal-header">
      <div class="header-inner">
        <router-link to="/portal/chat" class="logo">OpsMind</router-link>
        <nav class="main-nav">
          <router-link to="/portal/chat" class="nav-link" active-class="nav-link--active">
            智能问答
          </router-link>
          <router-link to="/portal/tickets/submit" class="nav-link" active-class="nav-link--active">
            提交申告
          </router-link>
          <router-link to="/portal/tickets" class="nav-link" active-class="nav-link--active">
            我的申告
          </router-link>
          <router-link to="/portal/messages" class="nav-link nav-link--badge" active-class="nav-link--active">
            消息
            <n-badge
              v-if="unreadCount > 0"
              :value="unreadCount"
              :max="99"
              size="tiny"
              class="msg-badge"
            />
          </router-link>
        </nav>
        <div class="header-right">
          <n-button quaternary circle size="small" @click="toggleTheme" title="切换主题">
            <template #icon>
              <n-icon size="18"><SunnyOutline v-if="isDark" /><MoonOutline v-else /></n-icon>
            </template>
          </n-button>
          <n-button text size="small" @click="router.push('/change-password')">修改密码</n-button>
          <n-button text size="small" @click="handleLogout">退出</n-button>
        </div>
      </div>
    </n-layout-header>
    <n-layout-content class="portal-main">
      <router-view />
    </n-layout-content>
  </n-layout>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { NLayout, NLayoutHeader, NLayoutContent, NButton, NIcon, NBadge } from 'naive-ui'
import { SunnyOutline, MoonOutline } from '@vicons/ionicons5'
import { useAuthStore } from '@/stores/auth'
import { useTheme } from '@/composables/useTheme'
import { useToast } from '@/composables/useToast'
import { getUnreadCount } from '@/api/message'

const router = useRouter()
const authStore = useAuthStore()
const { toggleTheme, isDark } = useTheme()
const toast = useToast()
const unreadCount = ref(0)

onMounted(async () => {
  try {
    const res = await getUnreadCount()
    const data = (res as any).data || res
    unreadCount.value = data?.count ?? data ?? 0
  } catch (err) {
    console.error('获取未读消息数失败', err)
    toast.showToast('消息计数加载失败', 'error')
  }
})

function handleLogout() {
  authStore.clearAuth()
  router.push('/login')
}
</script>

<style scoped>
.portal-layout {
  min-height: 100vh;
}

.portal-header {
  position: sticky;
  top: 0;
  z-index: 50;
}

.header-inner {
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 var(--spacing-lg);
  height: 56px;
  display: flex;
  align-items: center;
  gap: var(--spacing-xl);
}

.logo {
  font-size: 18px;
  font-weight: var(--font-weight-strong);
  color: var(--accent);
  text-decoration: none;
  flex-shrink: 0;
  letter-spacing: -0.3px;
}

.main-nav {
  display: flex;
  gap: var(--spacing-xs);
  flex: 1;
}

.nav-link {
  color: var(--text-secondary);
  text-decoration: none;
  font-size: 14px;
  font-weight: var(--font-weight-emphasis);
  padding: 8px 16px;
  border-radius: var(--radius-md);
  transition: color var(--transition-fast), background var(--transition-fast);
  position: relative;
}

.nav-link:hover {
  color: var(--text-primary);
  background: var(--bg-overlay);
}

.nav-link--active {
  color: var(--text-primary);
  background: var(--bg-overlay);
}

.nav-link--badge {
  display: inline-flex;
  align-items: center;
  gap: 6px;
}

.header-right {
  display: flex;
  gap: var(--spacing-sm);
  align-items: center;
  flex-shrink: 0;
}

.portal-main {
  max-width: 1200px;
  margin: 0 auto;
  padding: var(--spacing-xl) var(--spacing-lg);
}
</style>

// web/src/components/layout/PortalLayout.tsx
/** PortalLayout — 门户端布局（顶栏导航 + 内容区）。 */

'use client';

import { useState, useEffect } from 'react';
import { usePathname, useRouter } from 'next/navigation';
import { useAuth } from '@/hooks/useAuth';
import { useTheme } from '@/hooks/useTheme';
import { getUnreadCount } from '@/lib/api/message';
import { AppleButton } from '@/components/ui/AppleButton';
import { MessageSquare, TicketPlus, ListTodo, Bot, Sun, Moon, Shield, LogOut } from 'lucide-react';

const NAV_ITEMS = [
  { path: '/portal/chat', label: '智能问答', icon: <Bot size={16} /> },
  { path: '/portal/tickets/new', label: '提交申告', icon: <TicketPlus size={16} /> },
  { path: '/portal/tickets', label: '我的申告', icon: <ListTodo size={16} /> },
  { path: '/portal/messages', label: '消息', icon: <MessageSquare size={16} /> },
];

export function PortalLayout({ children }: { children: React.ReactNode }) {
  const { user, logout, menus } = useAuth();
  const { theme, toggleTheme } = useTheme();
  const pathname = usePathname();
  const router = useRouter();
  const [unreadCount, setUnreadCount] = useState(0);
  const isAdmin = menus.length > 0;

  useEffect(() => {
    const fetch = () => { getUnreadCount().then((d) => setUnreadCount(d.count)).catch(() => {}); };
    fetch();
    const t = setInterval(fetch, 30000);
    return () => clearInterval(t);
  }, []);

  return (
    <div style={{ minHeight: '100vh', background: 'var(--bg-parchment)' }}>
      <header style={{
        height: 52, background: 'var(--bg-canvas)', borderBottom: '1px solid var(--hairline)',
        display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '0 24px',
        position: 'sticky', top: 0, zIndex: 100, backdropFilter: 'saturate(180%) blur(20px)',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 32 }}>
          <span onClick={() => router.push('/portal/chat')} style={{ fontSize: 21, fontWeight: 600, letterSpacing: '0.231px', color: 'var(--text-ink)', cursor: 'pointer' }}>
            OpsMind
          </span>
          <nav style={{ display: 'flex', gap: 4 }}>
            {NAV_ITEMS.map((item) => {
              const active = pathname === item.path || pathname.startsWith(item.path + '/');
              return (
                <button key={item.path} onClick={() => router.push(item.path)} style={{
                  display: 'flex', alignItems: 'center', gap: 6, padding: '6px 14px',
                  border: 'none', background: active ? 'var(--divider-soft)' : 'transparent',
                  color: active ? 'var(--accent)' : 'var(--text-ink)', fontSize: 14,
                  fontWeight: active ? 600 : 400, borderRadius: 'var(--radius-sm)', cursor: 'pointer', position: 'relative',
                }}>
                  {item.icon} {item.label}
                  {item.label === '消息' && unreadCount > 0 && (
                    <span style={{ position: 'absolute', top: -4, right: -6, background: 'var(--color-error)', color: '#fff', fontSize: 10, fontWeight: 600, width: 18, height: 18, borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                      {unreadCount > 99 ? '99' : unreadCount}
                    </span>
                  )}
                </button>
              );
            })}
          </nav>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <button onClick={toggleTheme} style={{ border: 'none', background: 'none', cursor: 'pointer', color: 'var(--text-ink)', display: 'flex', padding: 4 }}>
            {theme === 'dark' ? <Sun size={18} /> : <Moon size={18} />}
          </button>
          {isAdmin && (
            <AppleButton variant="utility" onClick={() => router.push('/admin/dashboard')}>
              <Shield size={14} style={{ marginRight: 4 }} /> 后台管理
            </AppleButton>
          )}
          <span style={{ fontSize: 13, color: 'var(--text-muted-48)' }}>{user?.real_name}</span>
          <button onClick={() => { logout(); router.push('/login'); }} style={{ border: 'none', background: 'none', cursor: 'pointer', color: 'var(--text-muted-48)', display: 'flex', alignItems: 'center', gap: 4, fontSize: 13 }}>
            <LogOut size={14} /> 登出
          </button>
        </div>
      </header>
      <main style={{ maxWidth: 1200, margin: '0 auto', padding: 24 }}>{children}</main>
    </div>
  );
}
